### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sam920829** [BlackKnight683/Tickety#1]
Loading commands...
Successfully loaded 9 commands!
Promise { <pending> }
Hint: hit control+c anytime to enter REPL.
Server is Ready!
(node:119) UnhandledPromiseRejectionWarning: Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/runner/bbb/node_modules/discord.js/src/client/websocket/WebSocketManager.js:258:15)
(node:119) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:119) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


**Comment by kushal525-aka-supercoder** [comment]
hey just go to developer portal and go to your bot and enable server member intent and one more in that section so that you can make your bot

**Comment by Live-happy-day-with-kushal** [comment]
**Go to developer portal and go to that bot that you have added in this source and go to bot section and enable privileged intent and server member intent to able to work the work.**

**Comment by sam920829** [comment]
?????????????

**Comment by BlackKnight683** [comment]
go to https://discord.com/developer/applications

go to your bot applications

enable these
![image](https://user-images.githubusercontent.com/75422863/110240918-64c8f400-7f4e-11eb-8c0d-eeb08cc84f27.png)

**Comment by sam920829** [comment]
(node:268) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
embed.footer.icon_url: Scheme "null" is not supported. Scheme must be one of ('http', 'https').
    at RequestHandler.execute (/home/runner/iiiiiii/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/iiiiiii/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
(node:268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:268) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

{help.js}

**Comment by sam920829** [comment]
@BlackKnight683

**Comment by gabrieltr0008** [comment]
> go to https://discord.com/developer/applications
> 
> go to your bot applications
> 
> enable these
> ![image](https://user-images.githubusercontent.com/75422863/110240918-64c8f400-7f4e-11eb-8c0d-eeb08cc84f27.png)

Thanks

**Comment by BlackKnight683** [comment]
+ You need both intents enabled or the icons won't load, Also if you have them enabled and it still errors...  join the **[discord server](https://discord.gg/S2GGa23)** and send the code of the file where it errors & I'll try to fix it :D
