### ISSUE TITLE
Help Pls 

### ISSUE THREAD

**Issue by Lida1606** [BlackKnight683/Tickety#13]
Error: Cannot find module 'node:events'
Require stack:
- C:\Users\pi\Desktop\Tickety-2\node_modules\discord.js\src\client\BaseClient.js
- C:\Users\pi\Desktop\Tickety-2\node_modules\discord.js\src\index.js
- C:\Users\pi\Desktop\Tickety-2\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:745:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:961:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:92:18)←[39m
    at Object.<anonymous> (C:\Users\pi\Desktop\Tickety-2\node_modules\←[4mdiscord.js←[24m\src\client\BaseClient.js:3:22)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1072:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:937:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:778:12)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:961:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\pi\\Desktop\\Tickety-2\\node_modules\\discord.js\\src\\client\\BaseClient.js'←[39m,
    ←[32m'C:\\Users\\pi\\Desktop\\Tickety-2\\node_modules\\discord.js\\src\\index.js'←[39m,
    ←[32m'C:\\Users\\pi\\Desktop\\Tickety-2\\index.js'←[39m
  ]
}

**Comment by Aayush-683** [comment]
Update your nodejs version to 16 or above
