### ISSUE TITLE
node commands.js and node index.js not working

### ISSUE THREAD

**Issue by Vaibhav-Naik-26** [BlackKnight683/Tickety#16]
I am using [REPLIT](https://replit.com) i forked the repl and now when i type `node commands.js` or `node index.js` then nothing happens

[SEE THE IMAGE](https://ibb.co/w6MJV5K)
![unknown](https://user-images.githubusercontent.com/94748147/163542313-c5210fde-8b5d-4b90-9462-7b536cfd8e9c.png)

**Comment by itsP33t** [comment]
Tbh, replit is pretty bad for discord bots, I recommend trying out something else

**Comment by Vaibhav-Naik-26** [comment]
huh, replit is best , the only thing is we must have patience and think calmly, replit is the best , and vs code too is also the best

**Comment by itsP33t** [comment]
There is lot of better hostings out there
