### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by flayereu** [BlackKnight683/Tickety#5]
![issue](https://user-images.githubusercontent.com/47247768/151980198-4ea3ccc2-3bcd-470f-857c-bce9ee8f1c89.png)
so i'm having this issue so if you have a solution i would really apprerciate it

**Comment by Aayush-683** [comment]
thats an issue with glitch
maybe try changing this in your code
```json
"scripts": {
    "start": "node index.js",
}
```

**Comment by flayereu** [comment]
![issue2](https://user-images.githubusercontent.com/47247768/151983132-45a8287a-5c32-4faf-9920-2fd7ebeece31.png)
now this appears

**Comment by Aayush-683** [comment]
you need to install packages and update nodejs version to 16

**Comment by flayereu** [comment]
can u mention what packages exactly
and how to update the nodejs version

**Comment by Aayush-683** [comment]
https://support.glitch.com/t/upgrading-node-on-glitch/12458
