### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by Lucas6635** [BlackKnight683/Tickety#6]
hi i wanted to know what is the prefix of the bot

**Comment by Aayush-683** [comment]
its a slash command bot
After correct setup, its commands should show up when u type `/` in your discord server

**Comment by Lucas6635** [comment]
it does not display

**Comment by Lucas6635** [comment]
However, I haven't touched anything on the command.

**Comment by Lucas6635** [comment]
https://gyazo.com/ecf672833724b6e7f4100176bf81c72e

look

**Comment by Lucas6635** [comment]
Oh yes and do you know how I can put a personalized status on the bot

**Comment by Aayush-683** [comment]
it can be done in the client.on ready event
Something like `client.user.setActivity("/help")`

**Comment by Lucas6635** [comment]
and i can put it where

**Comment by Aayush-683** [comment]
https://github.com/BlackKnight683/Tickety/blob/v2/events/ready.js

**Comment by Lucas6635** [comment]
ok thank you it works but on the other hand the slash command does not work

**Comment by Lucas6635** [comment]
and I can configure a prefix of it

**Comment by Aayush-683** [comment]
you cannot.
Also did u invite the bot using the application.commands content?

**Comment by Lucas6635** [comment]
no

**Comment by Lucas6635** [comment]
and how can i do it

**Comment by Aayush-683** [comment]
Follow the tutorial vid

**Comment by Aayush-683** [comment]
https://youtu.be/sqDhfHhXjOA

**Comment by Lucas6635** [comment]
https://gyazo.com/62d582dca62c6aa17b969eb1c86ee2d9

its me but its

**Comment by Lucas6635** [comment]
you know where it comes from

**Comment by Aayush-683** [comment]
yeah it's from some discord library update, I'll fix it soon. should not affect the bot tho

**Comment by Lucas6635** [comment]
ok so that's why the commands don't work

**Comment by Aayush-683** [comment]
no, it will not stop the command from working

**Comment by Lucas6635** [comment]
and how do I change the type of status like stream watch

**Comment by Lucas6635** [comment]
and can i make a status that changes every minute

**Comment by Lucas6635** [comment]
?

**Comment by Lucas6635** [comment]
hello and can i make a status that changes every minute

**Comment by Aayush-683** [comment]
Closed due to inactivity
