### ISSUE TITLE
'DISALLOWED_INTENTS'

### ISSUE THREAD

**Issue by HarshaVarrdan** [BlackKnight683/Tickety#9]
![image](https://user-images.githubusercontent.com/44633197/155187047-dbc97321-b6c2-4702-8da2-ace96f278364.png)

Need help with this issue

**Comment by Aayush-683** [comment]
turn on privileged intents

**Comment by crossfire151** [comment]
> ![image](https://user-images.githubusercontent.com/44633197/155187047-dbc97321-b6c2-4702-8da2-ace96f278364.png)
> 
> Need help with this issue

1. visit https://discord.com/developers/applications
2. goto your application
3. goto BOT
4. toggle on every "INTENT" related toggle.
5. DELETE YOUR POST IN MY TOPIC, STOP INVADING PEOPLES POSTS!!! -> https://github.com/BlackKnight683/Tickety/issues/7
